### PR TITLE
Issue #9 feat: Sidebar and other layouts update

### PR DESCRIPTION
**Pull request by lakhanmandloi**

### CODE REVIEW

**Comment by lakhanmandloi** [comment]
Hi @coolbung ,

Here is the new design for the posts .

**Comment by coolbung** [comment]
The new sidebar looks great. So I just need to merge this MR now ?

**Comment by lakhanmandloi** [comment]
Yes. 

Should i go ahead and create preview site just like sunbird ? So that the reviewer & contributor knows the outcome.

**Comment by coolbung** [comment]
Sure.

**Pull request merged**
